# Regression Problem

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]] , columns=['cgpa','profile_score','lpa'])

In [5]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [23]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters={}
    L = len(layer_dims)
    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1] , layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[1],1))

    return parameters
    

In [24]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.],
        [0.]])}

In [25]:
def linear_forward(A_prev , W , b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [32]:
# This is the main function for forward propagation 
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2    # Number of layers in the neural network
    for  l in range(1 , L+1):
        A_prev = A
        w1 = parameters['W' + str(1)]
        b1 = parameters['b' + str(1)]

        print('A' +str(l-1) +":", A_prev)
        print("W" + str(l)+":",w1)
        print("b"+str(l)+":",b1)
        print("--"*20)

        A = linear_forward(A_prev , w1 , b1)
        print("A" + str(l)+":",A)
        print("**"*20)

    return A,A_prev
    

In [36]:
X = df[['cgpa' , 'profile_score']].values[0].reshape(2,1)  # Shape(no of features , no  of triaining example)
y = df[['lpa']].values[0][0]

# Paramter initialization
parameters = initialize_parameters([2,2,1])
# X
# L_layer_forward(X, parameters)
y_hat,A1 = L_layer_forward(X, parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
----------------------------------------
A2: [[0.32]
 [0.32]]
****************************************


In [37]:
y

np.int64(4)

In [38]:
y_hat = y_hat[0][0]

In [39]:
A1

array([[1.6],
       [1.6]])

In [42]:
update_parameters(parameters,y,y_hat,A1,X)

In [41]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [43]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
----------------------------------------
A2: [[0.32]
 [0.32]]
****************************************


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136],
        [0.      ]])}

In [44]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b2: [[0.00082267]
 [0.00082267]]
----------------------------------------
A2: [[0.36450487]
 [0.36450487]]
****************************************


{'W1': array([[0.1148618 , 0.11722763],
        [0.1148618 , 0.11722763]]),
 'b1': array([[0.00200559],
        [0.00200559]]),
 'W2': array([[0.12759346],
        [0.12759346]]),
 'b2': array([[0.13686445],
        [0.        ]])}

In [45]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[ 6]
 [10]]
W1: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b1: [[0.00200559]
 [0.00200559]]
----------------------------------------
A1: [[1.83979431]
 [1.87764768]]
****************************************
A1: [[1.83979431]
 [1.87764768]]
W2: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b2: [[0.00200559]
 [0.00200559]]
----------------------------------------
A2: [[0.42899765]
 [0.43779251]]
****************************************


{'W1': array([[0.12476208, 0.1337281 ],
        [0.12479027, 0.13377509]]),
 'b1': array([[0.00365564],
        [0.00366034]]),
 'W2': array([[0.14809246],
        [0.14851422]]),
 'b2': array([[0.15965623],
        [0.        ]])}

In [46]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0: [[ 5]
 [12]]
W1: [[0.12476208 0.1337281 ]
 [0.12479027 0.13377509]]
b1: [[0.00365564]
 [0.00366034]]
----------------------------------------
A1: [[2.12494929]
 [2.27760195]]
****************************************
A1: [[2.12494929]
 [2.27760195]]
W2: [[0.12476208 0.1337281 ]
 [0.12479027 0.13377509]]
b2: [[0.00365564]
 [0.00366034]]
----------------------------------------
A2: [[0.55299129]
 [0.59251218]]
****************************************


{'W1': array([[0.13607604, 0.1608816 ],
        [0.13625832, 0.1612984 ]]),
 'b1': array([[0.00591843],
        [0.00595394]]),
 'W2': array([[0.17549159],
        [0.17788166]]),
 'b2': array([[0.19077568],
        [0.        ]])}

In [47]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
----------------------------------------
A2: [[0.32]
 [0.32]]
****************************************
A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b2: [[0.00082267]
 [0.00082267]]
----------------------------------------
A2: [[0.36450487]
 [0.36450487]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.1148618  0.11722763]
 [0.1148618  0.11722763]]
b1: [[0.00200559]
 [0.00200559]]
----------------------------------------
A1: [[1.83979431]
 [1.87764768]]
****************************************


{'W1': array([[0.33329713, 0.49495871],
        [0.35907058, 0.54086843]]),
 'b1': array([[0.03836736],
        [0.04272922]]),
 'W2': array([[0.52455618],
        [0.64075209]]),
 'b2': array([[0.64511188],
        [0.        ]])}

## Verifying using Keras 


In [49]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [48]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

D:\JUPYTER NOTEBOOK\DEEP LEARNING\dl_env\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [53]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

D:\JUPYTER NOTEBOOK\DEEP LEARNING\dl_env\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [54]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.get_weights()

[array([[-0.5820425 , -0.2687834 ],
        [ 0.12844956, -1.218205  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2911595 ],
        [ 0.59347236]], dtype=float32),
 array([0.], dtype=float32)]

In [56]:
new_weights = [np.array([[0.1, 0.1],
                        [0.1, 0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [57]:
model.get_weights()

[array([[-0.5820425 , -0.2687834 ],
        [ 0.12844956, -1.218205  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2911595 ],
        [ 0.59347236]], dtype=float32),
 array([0.], dtype=float32)]

In [58]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [59]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 168.6881  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.5149 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 162.2778 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 159.2176 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 156.2141 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 152.8976 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.0637 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.0390 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 144.0972 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 141.0683 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.3571 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 135.3514
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 132.7654 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 130.0794 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.1727 
Epoc

In [60]:
model.get_weights()

[array([[-0.8664538 , -0.0538058 ],
        [-0.14386949, -1.011315  ]], dtype=float32),
 array([-0.281122  ,  0.21313033], dtype=float32),
 array([[-0.598362 ],
        [ 0.3775079]], dtype=float32),
 array([0.2376259], dtype=float32)]

# Classification Problem

In [61]:
 df1 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [62]:
df1

,cgpa,profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [63]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [64]:
# Utility Functions
def sigmoid(Z):
  
  A = 1/(1+np.exp(-Z))

  return A

In [65]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b

  A = sigmoid(Z)
  
  return A

In [66]:
# L-layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev


In [67]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [73]:
X = df1[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [74]:
X = df1[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.568725622654268


{'W1': array([[0.10000937, 0.10001059],
        [0.10000937, 0.10001059]]),
 'b1': array([[1.24770113e-06],
        [1.24770113e-06]]),
 'W2': array([[0.10007424],
        [0.10007424]]),
 'b2': array([[0.10011761]])}

In [75]:
X = df1[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8353333695154365


{'W1': array([[0.10000463, 0.10000267],
        [0.10000463, 0.10000267]]),
 'b1': array([[4.56125378e-07],
        [4.56135584e-07]]),
 'W2': array([[0.10002712],
        [0.10002712]]),
 'b2': array([[0.09997049]])}

In [76]:
X = df1[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df1[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8238180133031612


{'W1': array([[0.09999911, 0.09999716],
        [0.09999911, 0.09999716]]),
 'b1': array([[-6.47175329e-07],
        [-6.47175081e-07]]),
 'W2': array([[0.09998609],
        [0.09998609]]),
 'b2': array([[0.09992997]])}

In [77]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df1[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df1[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7103199085929446
Epoch -  2 Loss -  0.6991702892802629
Epoch -  3 Loss -  0.6991679314811485
Epoch -  4 Loss -  0.6991655746710999
Epoch -  5 Loss -  0.6991632188496667
Epoch -  6 Loss -  0.699160864016399
Epoch -  7 Loss -  0.6991585101708473
Epoch -  8 Loss -  0.6991561573125619
Epoch -  9 Loss -  0.6991538054410936
Epoch -  10 Loss -  0.6991514545559935
Epoch -  11 Loss -  0.6991491046568126
Epoch -  12 Loss -  0.6991467557431024
Epoch -  13 Loss -  0.6991444078144144
Epoch -  14 Loss -  0.6991420608703007
Epoch -  15 Loss -  0.6991397149103132
Epoch -  16 Loss -  0.6991373699340042
Epoch -  17 Loss -  0.6991350259409265
Epoch -  18 Loss -  0.6991326829306324
Epoch -  19 Loss -  0.6991303409026751
Epoch -  20 Loss -  0.699127999856608
Epoch -  21 Loss -  0.6991256597919842
Epoch -  22 Loss -  0.6991233207083575
Epoch -  23 Loss -  0.6991209826052818
Epoch -  24 Loss -  0.699118645482311
Epoch -  25 Loss -  0.6991163093389996
Epoch -  26 Loss -  0.699113974174902

{'W1': array([[0.09994267, 0.09984548],
        [0.09994272, 0.09984548]]),
 'b1': array([[-3.38405750e-05],
        [-3.38419977e-05]]),
 'W2': array([[0.09920806],
        [0.09920816]]),
 'b2': array([[0.09915209]])}

# Classification Using keras

In [79]:
model1 = Sequential()
model1.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

D:\JUPYTER NOTEBOOK\DEEP LEARNING\dl_env\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [80]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (128.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20 (84.00 B)

In [81]:
model.get_weights()

[array([[-0.8664538 , -0.0538058 ],
        [-0.14386949, -1.011315  ]], dtype=float32),
 array([-0.281122  ,  0.21313033], dtype=float32),
 array([[-0.598362 ],
        [ 0.3775079]], dtype=float32),
 array([0.2376259], dtype=float32),
 array([[0.31964505]], dtype=float32),
 array([0.], dtype=float32)]

In [83]:
new_weights = [np.array([[0.1, 0.1],
                        [0.1, 0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [84]:
model.get_weights()

[array([[-0.8664538 , -0.0538058 ],
        [-0.14386949, -1.011315  ]], dtype=float32),
 array([-0.281122  ,  0.21313033], dtype=float32),
 array([[-0.598362 ],
        [ 0.3775079]], dtype=float32),
 array([0.2376259], dtype=float32),
 array([[0.31964505]], dtype=float32),
 array([0.], dtype=float32)]

In [85]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [89]:
model.fit(df1.iloc[:,0:-1].values,df1['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6437 
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6433 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6436 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6432 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6430 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6421 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6424 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6433 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6426 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6420 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6410 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6409 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6405 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6405 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6403 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━